### ISSUE TITLE
请问是否有人复现成功，想问一下结果是否有出入？

### ISSUE THREAD

**Issue by ytuv** [vietthanh2710/AC_MambaSeg#5]
以下是我复现出来的部分结果，各项指标均不在正常范围内，可以说是很低，想请教一下复现出来的大佬，你们的结果是否与论文中结果一致，在源码的基础上是否进行了改动？或者是数据集的问题？（我的isic2018数据集有2694张图片），非常感谢！
The following are some of the results I reproduced. The indicators are not within the normal range, which can be said to be very low. I would like to ask the reproduced boss, is your result consistent with the results in the paper, and has it been changed based on the source code? Or is it a problem with the dataset? (My isic2018 dataset has 2694 images), thank you very much!

**Comment by vietthanh2710** [comment]
Should you check the version of some libraries because it may cause some conflicts? I have just been casually used the ISIC2018 dataset which is resized to 256 x 256 and saved as npz files.
